//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnlimitedSagaCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnlimitedSagaCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Modifier:.
        /// </summary>
        public static string AbilityModifierLabel {
            get {
                return ResourceManager.GetString("AbilityModifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory One:.
        /// </summary>
        public static string AccessoryOneLabel {
            get {
                return ResourceManager.GetString("AccessoryOneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory One Weight:.
        /// </summary>
        public static string AccessoryOneWeightLabel {
            get {
                return ResourceManager.GetString("AccessoryOneWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory Two:.
        /// </summary>
        public static string AccessoryTwoLabel {
            get {
                return ResourceManager.GetString("AccessoryTwoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory Two Weight:.
        /// </summary>
        public static string AccessoryTwoWeightLabel {
            get {
                return ResourceManager.GetString("AccessoryTwoWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Combo.
        /// </summary>
        public static string AddToComboLabel {
            get {
                return ResourceManager.GetString("AddToComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllLabel {
            get {
                return ResourceManager.GetString("AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquan.
        /// </summary>
        public static string Aquan {
            get {
                return ResourceManager.GetString("Aquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack:.
        /// </summary>
        public static string AttackColonLabel {
            get {
                return ResourceManager.GetString("AttackColonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Damage (For LP Calc):.
        /// </summary>
        public static string AttackDamageLabel {
            get {
                return ResourceManager.GetString("AttackDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker.
        /// </summary>
        public static string AttackerLabel {
            get {
                return ResourceManager.GetString("AttackerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string AttackLabel {
            get {
                return ResourceManager.GetString("AttackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Type:.
        /// </summary>
        public static string AttackTypeLabel {
            get {
                return ResourceManager.GetString("AttackTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes:.
        /// </summary>
        public static string AttributesLabel {
            get {
                return ResourceManager.GetString("AttributesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe.
        /// </summary>
        public static string Axe {
            get {
                return ResourceManager.GetString("Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Value:.
        /// </summary>
        public static string BaseValueLabel {
            get {
                return ResourceManager.GetString("BaseValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast.
        /// </summary>
        public static string Beast {
            get {
                return ResourceManager.GetString("Beast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird.
        /// </summary>
        public static string Bird {
            get {
                return ResourceManager.GetString("Bird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string BonusLabel {
            get {
                return ResourceManager.GetString("BonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss.
        /// </summary>
        public static string Boss {
            get {
                return ResourceManager.GetString("Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        public static string Bow {
            get {
                return ResourceManager.GetString("Bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string CalculateLabel {
            get {
                return ResourceManager.GetString("CalculateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character:.
        /// </summary>
        public static string CharacterColonLabel {
            get {
                return ResourceManager.GetString("CharacterColonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string CharacterLabel {
            get {
                return ResourceManager.GetString("CharacterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Stat Calculator.
        /// </summary>
        public static string CharacterStatCalculatorLabel {
            get {
                return ResourceManager.GetString("CharacterStatCalculatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Weight:.
        /// </summary>
        public static string CharacterWeightLabel {
            get {
                return ResourceManager.GetString("CharacterWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest:.
        /// </summary>
        public static string ChestLabel {
            get {
                return ResourceManager.GetString("ChestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest Weight:.
        /// </summary>
        public static string ChestWeightLabel {
            get {
                return ResourceManager.GetString("ChestWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Defense:.
        /// </summary>
        public static string ColdDefenseLabel {
            get {
                return ResourceManager.GetString("ColdDefenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Damage:.
        /// </summary>
        public static string ComboDamageLabel {
            get {
                return ResourceManager.GetString("ComboDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Percentage (1.00 = 100%):.
        /// </summary>
        public static string ComboPercentageLabel {
            get {
                return ResourceManager.GetString("ComboPercentageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current HP:.
        /// </summary>
        public static string CurrentHpLabel {
            get {
                return ResourceManager.GetString("CurrentHpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagger.
        /// </summary>
        public static string Dagger {
            get {
                return ResourceManager.GetString("Dagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Calculator.
        /// </summary>
        public static string DamageCalculatorLabel {
            get {
                return ResourceManager.GetString("DamageCalculatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability:.
        /// </summary>
        public static string DamageProbabilityLabel {
            get {
                return ResourceManager.GetString("DamageProbabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demon.
        /// </summary>
        public static string Demon {
            get {
                return ResourceManager.GetString("Demon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        public static string Dragon {
            get {
                return ResourceManager.GetString("Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durability:.
        /// </summary>
        public static string DurabilityLabel {
            get {
                return ResourceManager.GetString("DurabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth:.
        /// </summary>
        public static string EarthLabel {
            get {
                return ResourceManager.GetString("EarthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN Cost:.
        /// </summary>
        public static string EnCostLabel {
            get {
                return ResourceManager.GetString("EnCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endurance:.
        /// </summary>
        public static string EnduranceLabel {
            get {
                return ResourceManager.GetString("EnduranceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy:.
        /// </summary>
        public static string EnemyColonLabel {
            get {
                return ResourceManager.GetString("EnemyColonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy.
        /// </summary>
        public static string EnemyLabel {
            get {
                return ResourceManager.GetString("EnemyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Modifier:.
        /// </summary>
        public static string EquipmentModifierLabel {
            get {
                return ResourceManager.GetString("EquipmentModifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familiar.
        /// </summary>
        public static string Familiar {
            get {
                return ResourceManager.GetString("Familiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Cost:.
        /// </summary>
        public static string FinalCostLabel {
            get {
                return ResourceManager.GetString("FinalCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Damage:.
        /// </summary>
        public static string FinalDamageLabel {
            get {
                return ResourceManager.GetString("FinalDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string FinalLabel {
            get {
                return ResourceManager.GetString("FinalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire:.
        /// </summary>
        public static string FireLabel {
            get {
                return ResourceManager.GetString("FireLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauntlet.
        /// </summary>
        public static string Gauntlet {
            get {
                return ResourceManager.GetString("Gauntlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth Rate:.
        /// </summary>
        public static string GrowthRateLabel {
            get {
                return ResourceManager.GetString("GrowthRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun.
        /// </summary>
        public static string Gun {
            get {
                return ResourceManager.GetString("Gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head:.
        /// </summary>
        public static string HeadLabel {
            get {
                return ResourceManager.GetString("HeadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Weight:.
        /// </summary>
        public static string HeadWeightLabel {
            get {
                return ResourceManager.GetString("HeadWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Defense:.
        /// </summary>
        public static string HeatDefenseLabel {
            get {
                return ResourceManager.GetString("HeatDefenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit.
        /// </summary>
        public static string Hit {
            get {
                return ResourceManager.GetString("Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Defense:.
        /// </summary>
        public static string HitDefenseLabel {
            get {
                return ResourceManager.GetString("HitDefenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP Damage Calculation.
        /// </summary>
        public static string HpDamageCalculation {
            get {
                return ResourceManager.GetString("HpDamageCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP Damage:.
        /// </summary>
        public static string HpDamageLabel {
            get {
                return ResourceManager.GetString("HpDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Equipment.
        /// </summary>
        public static string InitialEquipmentLabel {
            get {
                return ResourceManager.GetString("InitialEquipmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insect.
        /// </summary>
        public static string Insect {
            get {
                return ResourceManager.GetString("Insect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation.
        /// </summary>
        public static string Investigation {
            get {
                return ResourceManager.GetString("Investigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Cost Calculator.
        /// </summary>
        public static string ItemCostCalculatorLabel {
            get {
                return ResourceManager.GetString("ItemCostCalculatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemLabel {
            get {
                return ResourceManager.GetString("ItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        public static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOTR.
        /// </summary>
        public static string Kotr {
            get {
                return ResourceManager.GetString("Kotr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs:.
        /// </summary>
        public static string LegLabel {
            get {
                return ResourceManager.GetString("LegLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs Weight:.
        /// </summary>
        public static string LegWeightLabel {
            get {
                return ResourceManager.GetString("LegWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Defense:.
        /// </summary>
        public static string LightDefenseLabel {
            get {
                return ResourceManager.GetString("LightDefenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning.
        /// </summary>
        public static string Lightning {
            get {
                return ResourceManager.GetString("Lightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning Defense:.
        /// </summary>
        public static string LightningDefenseLabel {
            get {
                return ResourceManager.GetString("LightningDefenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LP Damage Calculation.
        /// </summary>
        public static string LpDamageCalculation {
            get {
                return ResourceManager.GetString("LpDamageCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LP Damage:.
        /// </summary>
        public static string LpDamageLabel {
            get {
                return ResourceManager.GetString("LpDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LP Defense:.
        /// </summary>
        public static string LpDefenseLabel {
            get {
                return ResourceManager.GetString("LpDefenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic.
        /// </summary>
        public static string Magic {
            get {
                return ResourceManager.GetString("Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic:.
        /// </summary>
        public static string MagicLabel {
            get {
                return ResourceManager.GetString("MagicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Type:.
        /// </summary>
        public static string MagicTypeLabel {
            get {
                return ResourceManager.GetString("MagicTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial.
        /// </summary>
        public static string Martial {
            get {
                return ResourceManager.GetString("Martial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mastery.
        /// </summary>
        public static string Mastery {
            get {
                return ResourceManager.GetString("Mastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string MaterialLabel {
            get {
                return ResourceManager.GetString("MaterialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material:.
        /// </summary>
        public static string MaterialWithColonLabel {
            get {
                return ResourceManager.GetString("MaterialWithColonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max HP:.
        /// </summary>
        public static string MaxHpLabel {
            get {
                return ResourceManager.GetString("MaxHpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        public static string Metal {
            get {
                return ResourceManager.GetString("Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal:.
        /// </summary>
        public static string MetalLabel {
            get {
                return ResourceManager.GetString("MetalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier.
        /// </summary>
        public static string MultiplierLabel {
            get {
                return ResourceManager.GetString("MultiplierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery.
        /// </summary>
        public static string Mystery {
            get {
                return ResourceManager.GetString("Mystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiation.
        /// </summary>
        public static string Negotiation {
            get {
                return ResourceManager.GetString("Negotiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Abilities:.
        /// </summary>
        public static string NumberOfAbilitiesLabel {
            get {
                return ResourceManager.GetString("NumberOfAbilitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Hits:.
        /// </summary>
        public static string NumberOfHitsLabel {
            get {
                return ResourceManager.GetString("NumberOfHitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 LP Damage Probability:.
        /// </summary>
        public static string OneDamageLabel {
            get {
                return ResourceManager.GetString("OneDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacifist.
        /// </summary>
        public static string Pacifist {
            get {
                return ResourceManager.GetString("Pacifist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Board.
        /// </summary>
        public static string PanelBoardLabel {
            get {
                return ResourceManager.GetString("PanelBoardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phobia.
        /// </summary>
        public static string Phobia {
            get {
                return ResourceManager.GetString("Phobia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierce.
        /// </summary>
        public static string Pierce {
            get {
                return ResourceManager.GetString("Pierce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierce Defense:.
        /// </summary>
        public static string PierceDefenseLabel {
            get {
                return ResourceManager.GetString("PierceDefenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch.
        /// </summary>
        public static string Punch {
            get {
                return ResourceManager.GetString("Punch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Damage:.
        /// </summary>
        public static string RawDamageLabel {
            get {
                return ResourceManager.GetString("RawDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        public static string RawLabel {
            get {
                return ResourceManager.GetString("RawLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ResultsLabel {
            get {
                return ResourceManager.GetString("ResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Boss.
        /// </summary>
        public static string ScenarioBoss {
            get {
                return ResourceManager.GetString("ScenarioBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal.
        /// </summary>
        public static string Seal {
            get {
                return ResourceManager.GetString("Seal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price:.
        /// </summary>
        public static string SellingPriceLabel {
            get {
                return ResourceManager.GetString("SellingPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Damage.
        /// </summary>
        public static string SetDamageLabel {
            get {
                return ResourceManager.GetString("SetDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        public static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill:.
        /// </summary>
        public static string SkillLabel {
            get {
                return ResourceManager.GetString("SkillLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slash.
        /// </summary>
        public static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slash Defense:.
        /// </summary>
        public static string SlashDefenseLabel {
            get {
                return ResourceManager.GetString("SlashDefenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slime.
        /// </summary>
        public static string Slime {
            get {
                return ResourceManager.GetString("Slime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spear.
        /// </summary>
        public static string Spear {
            get {
                return ResourceManager.GetString("Spear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit:.
        /// </summary>
        public static string SpiritLabel {
            get {
                return ResourceManager.GetString("SpiritLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Panels.
        /// </summary>
        public static string StartingPanelsLabel {
            get {
                return ResourceManager.GetString("StartingPanelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength:.
        /// </summary>
        public static string StrengthLabel {
            get {
                return ResourceManager.GetString("StrengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword.
        /// </summary>
        public static string Sword {
            get {
                return ResourceManager.GetString("Sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 LP Damage Probability:.
        /// </summary>
        public static string ThreeDamageLabel {
            get {
                return ResourceManager.GetString("ThreeDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw.
        /// </summary>
        public static string Throw {
            get {
                return ResourceManager.GetString("Throw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Weight:.
        /// </summary>
        public static string TotalWeightLabel {
            get {
                return ResourceManager.GetString("TotalWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string TransferLabel {
            get {
                return ResourceManager.GetString("TransferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 LP Damage Probability:.
        /// </summary>
        public static string TwoDamageLabel {
            get {
                return ResourceManager.GetString("TwoDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TypeWithColonLabel {
            get {
                return ResourceManager.GetString("TypeWithColonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undead.
        /// </summary>
        public static string Undead {
            get {
                return ResourceManager.GetString("Undead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegeplast.
        /// </summary>
        public static string Vegeplast {
            get {
                return ResourceManager.GetString("Vegeplast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water:.
        /// </summary>
        public static string WaterLabel {
            get {
                return ResourceManager.GetString("WaterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Material:.
        /// </summary>
        public static string WeaponMaterialLabel {
            get {
                return ResourceManager.GetString("WeaponMaterialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon One:.
        /// </summary>
        public static string WeaponOneLabel {
            get {
                return ResourceManager.GetString("WeaponOneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon One Weight:.
        /// </summary>
        public static string WeaponOneWeightLabel {
            get {
                return ResourceManager.GetString("WeaponOneWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Power:.
        /// </summary>
        public static string WeaponPowerLabel {
            get {
                return ResourceManager.GetString("WeaponPowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Two:.
        /// </summary>
        public static string WeaponTwoLabel {
            get {
                return ResourceManager.GetString("WeaponTwoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Two Weight:.
        /// </summary>
        public static string WeaponTwoWeightLabel {
            get {
                return ResourceManager.GetString("WeaponTwoWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Type:.
        /// </summary>
        public static string WeaponTypeLabel {
            get {
                return ResourceManager.GetString("WeaponTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Calculator.
        /// </summary>
        public static string WeightCalculatorLabel {
            get {
                return ResourceManager.GetString("WeightCalculatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        public static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string WeightNoColonLabel {
            get {
                return ResourceManager.GetString("WeightNoColonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildling.
        /// </summary>
        public static string Wildling {
            get {
                return ResourceManager.GetString("Wildling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood:.
        /// </summary>
        public static string WoodLabel {
            get {
                return ResourceManager.GetString("WoodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 LP Damage Probability:.
        /// </summary>
        public static string ZeroDamageLabel {
            get {
                return ResourceManager.GetString("ZeroDamageLabel", resourceCulture);
            }
        }
    }
}
